### ISSUE TITLE
Count number of values in tables for ETL

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/unizin-validation#2]
We want to have a count of the values in the tables needed for the ETL process. @zqian will provide the tables.

According to IQ data mapping document: here are the list of relevant UDW tables:
COURSE_DIM, ASSIGNMENT_DIM, USER_DIM, SUBMISSION_FACT, SUBMISSION_DIM, SUBMISSION_COMMENT_DIM,ENROLLMENT_TERM_DIM, SCORE_FACT,PSEUDONYM_DIM,

**Comment by jonespm** [comment]
This could also probably just check all of the tables counts. There's for sure a command to get all tables, then we'd just iterate over them.

**Comment by zqian** [comment]
Looks good to me! I thought there should be a "flag setting" step so that if any of those table count is zero, the warning flag should be set true, and surfaced via Jenkins endpoint. 

Maybe embed the task in another issue?

**Comment by ssciolla** [comment]
This has been resolved by PR #7. Work on flags/checks has moved to issue #8.
